### ISSUE TITLE
My answer was marked wrong incorrectly.

### ISSUE THREAD

**Issue by dovid11564** [learn-co-curriculum/phase-1-quiz-scope#2] opened 2022-09-22 13:26 UTC
### Canvas Link

https://learning.flatironschool.com/courses/5234/quizzes/37552

### Concern

For question 7, "All variables and functions declared in outer scopes are available in inner scopes via the scope chain.", I answered false, since variables declared with var cannot be accessed via global scope. It got marked as wrong, so 0 spoke to my instructor and he agreed with me that the test marked my answer wrong incorrectly.

**Comment by lizbur10** [comment] 2022-10-04 20:39
Hi @dovid11564 ! Thanks for providing this feedback. I've taken a look back at the question and I do believe it's correct as is. Any variable declared in the global scope, regardless of how it's declared, is accessible to any inner functions or code blocks. 

It is true you could declare a variable with the same name as a global variable inside a function or code block and no longer be able to access the value of the outer variable by name. However, that issue is related to the problems with using `var` and has nothing to do with the scope chain. It is basically breaking the code so that it no longer works as intended (which is one of the reasons `let` and `const` were added).

I hope this clarifies things. I'm going to go ahead and close this issue but please feel free to reopen it if you still feel the question is flawed.

Thanks for contributing to the Flatiron School curriculum 💙

**Closed as completed by lizbur10** 2022-10-04 20:39 UTC
Labels: se curriculum
